import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
export const metadata: Metadata = {
  title: "Donation Policy",
  description: "How domestic donations are accepted, designated, recorded and acknowledged by Amaana Foundation.",
  alternates: { canonical: "/donation-policy" },
  openGraph: { type: "website", url: "/donation-policy", title: "Donation Policy | Amaana Foundation", description: "How Amaana accepts and records domestic donations." },
  twitter: { card: "summary", title: "Donation Policy | Amaana Foundation", description: "How Amaana accepts and records domestic donations." },
};
const sections=[
["01","Domestic contributions only",<>The checkout requires confirmation that funds are being contributed from an Indian source through a domestic payment method. <strong>Foreign contributions are not invited or accepted because Amaana Foundation is not FCRA-registered.</strong></>],
["02","Designated purpose",<>A donation created through an appeal checkout is recorded against that specific appeal. Amaana does not silently redirect a designated contribution to another cause. If a purpose can no longer proceed, the matter must be handled through the applicable donor, accounting and compliance process.</>],
["03","Fully funded or closed appeals",<>Once an appeal reaches its approved target or is otherwise closed to fundraising, new designated checkout is stopped. The appeal may remain visible as an accountability record even though it is no longer accepting designated donations.</>],
["04","Payment confirmation",<>Razorpay processes checkout. A donation is counted as successful only after server-side verification and confirmation of the captured payment. Failed, abandoned or unverified orders are not added to an appeal&apos;s confirmed collection total.</>],
["05","Collection totals and reconciliation",<>Displayed collection totals reflect confirmed captured payments, adjusted for processed refunds. Administrative or payment-provider reconciliation may cause short delays before a status or total is updated.</>],
["06","Zakat designation",<>An appeal or fund is described as Zakat-eligible only when Amaana has specifically reviewed and approved that designation. Zakat eligibility is never inferred from an appeal title, category or beneficiary story.</>],
["07","Privacy preference",<>Donors may request public anonymity. Amaana will still retain the identity and transaction information needed for payment, accounting, security and applicable compliance records.</>],
["08","Acknowledgement and tax status",<>After confirmed payment, the platform provides a normal donation acknowledgement. <strong>It is not presented as an 80G tax-deduction certificate.</strong> Amaana&apos;s current Section 80G approval is provisional; the platform does not guarantee tax deductibility for every contribution.</>]
] as const;
export default function DonationPolicyPage(){return <div className="v2-policy-page v2-policy-giving"><PageHero variant="trust" eyebrow="Trust & Policies" title="Give with clarity." description={<p>Amaana currently accepts domestic INR donations through supported giving routes. The rules below explain designation, appeal closure, payment confirmation and acknowledgement.</p>} visualKicker="Donation Policy" visualTitle="Responsible Giving" visualNote="Clear boundaries for how support is accepted, designated, recorded and acknowledged."/><section className="v2-policy-principles"><div className="v2-shell"><div><span>Source</span><strong>Domestic Indian contributions only.</strong></div><div><span>Purpose</span><strong>Donor designation is not silently changed.</strong></div><div><span>Confirmation</span><strong>Only verified captured payments count.</strong></div></div></section><section className="v2-policy-body"><div className="v2-shell v2-policy-layout"><aside><p>Donation policy</p><strong>Trust is not only about where support goes. It is also about being precise about how it is received, designated and recorded.</strong><Link href="/appeals">See verified appeals →</Link><Link href="/refund-policy">Refund policy →</Link><Link href="/compliance">Compliance position →</Link></aside><div className="v2-policy-sections">{sections.map(([n,title,body])=><article key={n}><span>{n}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></div></section></div>}
