import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Compliance and Registration", description: "Current donation and tax-approval disclosures for Amaana Foundation." };

export default function CompliancePage() {
  return <div className="v2-home v2-compliance-page">
    <section className="v2-compliance-hero"><div className="v2-shell v2-compliance-hero-grid"><div><p className="v2-section-label">Current position · stated conservatively</p><h1>Clarity before<br />claims.</h1><p>This page explains Amaana Foundation&apos;s current donation and tax-approval position using only what is presently confirmed. Where professional confirmation is still pending, the site says so.</p><div className="v2-hero-actions"><a className="v2-button" href="#current-position">See current position</a><Link className="v2-text-link" href="/transparency">Transparency approach →</Link></div></div><div className="v2-compliance-seal"><span>Current public position</span><strong>Domestic<br />donations<br />only</strong><small>No FCRA registration</small></div></div></section>

    <section className="v2-compliance-strip"><div className="v2-shell"><article><span>Domestic giving</span><strong>Accepted</strong><p>Through supported Indian payment methods.</p></article><article><span>Foreign contribution</span><strong>Not accepted</strong><p>Amaana Foundation is not presently FCRA-registered.</p></article><article><span>80G</span><strong>Provisional approval</strong><p>Form 10AC dated 26 January 2026.</p></article><article><span>Tax certificate</span><strong>Not enabled</strong><p>Normal donation acknowledgements only at present.</p></article></div></section>

    <section className="v2-section paper" id="current-position"><div className="v2-shell"><div className="v2-section-head"><div><p className="v2-section-label">Current public position</p><h2 className="v2-section-title">What Amaana can state today.</h2></div><p className="v2-section-intro">These disclosures are intentionally narrower than a marketing claim. They are designed to stay accurate as the Foundation&apos;s compliance position evolves.</p></div><div className="v2-compliance-ledger"><article><span>01</span><div><small>Donations</small><h3>Domestic Indian sources only</h3><p>Amaana Foundation currently accepts donations only from domestic Indian sources through supported Indian payment methods.</p></div></article><article><span>02</span><div><small>FCRA</small><h3>Foreign contributions are not invited or accepted</h3><p>Amaana Foundation is not presently registered under the Foreign Contribution (Regulation) Act. The platform therefore does not invite or accept foreign contributions.</p></div></article><article><span>03</span><div><small>Section 80G</small><h3>Provisional approval is in place</h3><p>Amaana Foundation received provisional approval under Section 80G through Form 10AC dated 26 January 2026, covering Assessment Years 2026–27 through 2028–29.</p></div></article><article><span>04</span><div><small>Donation acknowledgements</small><h3>No 80G tax-deduction certificate is issued by the platform</h3><p>The platform currently issues normal donation acknowledgements only. These acknowledgements do not claim or certify eligibility for an income-tax deduction under Section 80G.</p></div></article></div></div></section>

    <section className="v2-section dark v2-compliance-pending"><div className="v2-shell v2-compliance-pending-grid"><div><p className="v2-section-label">Pending professional confirmation</p><h2 className="v2-section-title">Some matters remain deliberately unresolved in public copy.</h2><p className="v2-section-intro">The Foundation is confirming its 12AB/12A position and the applicable process and timeline for conversion or renewal of provisional 80G approval with its chartered accountant.</p></div><div className="v2-compliance-hold"><span>Control currently applied</span><strong>Tax-certificate functionality remains disabled.</strong><p>It will stay disabled until the required position and controls are professionally confirmed.</p></div></div></section>

    <section className="v2-section v2-compliance-guardrails"><div className="v2-shell"><div className="v2-section-head"><div><p className="v2-section-label">Public guardrails</p><h2 className="v2-section-title">What the platform refuses to imply.</h2></div><p className="v2-section-intro">Trust is strengthened by making the limits visible instead of burying them in small print.</p></div><div className="v2-compliance-guardrail-grid"><article><span>01</span><h3>No FCRA claim</h3><p>Foreign contributions are not solicited or accepted.</p></article><article><span>02</span><h3>No final/permanent 80G claim</h3><p>The current approval is presented as provisional, not permanent.</p></article><article><span>03</span><h3>No automatic tax promise</h3><p>A normal acknowledgement is not described as a deduction certificate.</p></article><article><span>04</span><h3>No guessing on 12AB/12A</h3><p>The public site waits for professional confirmation rather than filling the gap with assumptions.</p></article></div></div></section>

    <section className="v2-compliance-note"><div className="v2-shell"><strong>Tax note</strong><p>Donors should obtain independent tax advice for their individual circumstances.</p></div></section>

    <section className="v2-closing"><div className="v2-shell"><p className="v2-section-label">Trust should be inspectable</p><h2>See the work, the evidence and the boundaries together.</h2><p>Compliance is one part of trust. Continue into Amaana&apos;s verification and transparency journeys for the wider accountability picture.</p><div className="v2-hero-actions" style={{justifyContent:"center"}}><Link className="v2-button" href="/transparency">Explore transparency</Link><Link className="v2-text-link" href="/how-we-verify">How we verify →</Link></div></div></section>
  </div>;
}
