import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { PolicyToc } from "@/components/policy-toc";
export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms governing use of the Amaana Foundation platform and assistance-request process.",
  alternates: { canonical: "/terms" },
  openGraph: { type: "website", url: "/terms", title: "Terms of Use | Amaana Foundation", description: "Terms for Amaana's public platform and assistance-request process." },
  twitter: { card: "summary", title: "Terms of Use | Amaana Foundation", description: "Terms for Amaana's public platform and assistance-request process." },
};
const sections=[
["01","Platform purpose",<>The platform provides information about Amaana Foundation, receives private assistance requests and enables domestic donations through supported giving routes.</>],
["02","No guaranteed assistance or fundraising",<>Submitting a request does not guarantee verification, approval, public publication, fundraising, a particular response time or assistance. A verified case may be supported privately, supported partially, referred, declined or considered for a public appeal.</>],
["03","Accurate and relevant information",<>Applicants should provide truthful, current and relevant information. Knowingly false, altered or misleading evidence may result in rejection, closure or withdrawal of support. Please do not submit unrelated documents, passwords, OTPs or unnecessary full financial credentials.</>],
["04","Private verification",<>Amaana may request documents or clarification, contact relevant institutions or referees, conduct local verification and compare information with other fundraising or support sources. Verification material is private by default.</>],
["05","Public appeal is a separate decision",<>Submission of a request or supporting documents does not grant permission to publish them. If Amaana considers a public appeal, public identity, photographs, sensitive medical or financial details, institution names and archive use are reviewed separately before publication.</>],
["06","Funding targets and other support",<>Where public fundraising is approved, the target is based on the verified need and available context. Requesters should disclose material parallel fundraising or other support so Amaana can reduce duplication or over-collection risk.</>],
["07","Zakat",<>A requester should not assume that a case will be marked Zakat-eligible. Zakat status is reviewed separately and is shown publicly only when Amaana has specifically approved that designation.</>],
["08","Medical and emergency boundaries",<>Amaana does not provide medical diagnosis or treatment advice and cannot guarantee a medical or financial outcome. The assistance process is not an ambulance, hospital or emergency service; immediate threats to life or safety should be directed to appropriate emergency services.</>],
["09","Payments",<>Domestic INR payments are processed through Razorpay and may also be subject to its terms. A payment is treated as confirmed only after successful server-side verification. See the Donation and Refund policies for current payment handling.</>],
["10","Availability and contact",<>The platform may be changed, suspended or temporarily unavailable for maintenance, security or operational reasons. Questions may be sent to <a href="mailto:amaanafoundation24@gmail.com">amaanafoundation24@gmail.com</a>.</>]
] as const;
export default function TermsPage(){return <div className="v2-policy-page v2-policy-terms"><PageHero variant="trust" eyebrow="Trust & Policies" title="Use the platform with integrity." description={<p>These terms state Amaana&apos;s current operating boundaries for public information, private assistance requests and domestic donation services. Final legal wording remains subject to professional review.</p>} visualKicker="Terms of Use" visualTitle="Clear Expectations" visualNote="Honesty, privacy and operational boundaries protect applicants, donors, the team and the integrity of the work."/><section className="v2-policy-principles"><div className="v2-shell"><div><span>Honesty</span><strong>Information submitted should be accurate.</strong></div><div><span>Privacy</span><strong>Requesting help does not grant publication consent.</strong></div><div><span>Boundaries</span><strong>A request is not a promise of funding.</strong></div></div></section><section className="v2-policy-body"><div className="v2-shell v2-policy-layout"><aside><p>Terms of use</p><strong>Clear expectations protect applicants, donors, the team and the integrity of the work.</strong><Link href="/privacy">Privacy notice →</Link><Link href="/how-we-verify">How we verify →</Link><Link href="/donation-policy">Donation policy →</Link><PolicyToc items={sections.map(([n,title])=>({id:`policy-${n}`,label:title}))}/></aside><div className="v2-policy-sections">{sections.map(([n,title,body])=><article id={`policy-${n}`} key={n}><span>{n}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></div></section></div>}
