import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Privacy Policy", description: "How Amaana Foundation collects, uses and protects personal information." };
const sections=[
["01","Information we collect",<>Assistance applicants may provide names, contact information, location, descriptions of need and supporting documents. Donors provide a name, email address, optional phone number, donation amount and payment references. Staff accounts contain identity, access-role and audit information.</>],
["02","How information is used",<>Information is used to verify requests, administer appeals, process and reconcile donations, communicate status changes, prevent misuse, maintain audit records and meet applicable obligations.</>],
["03","Payment information",<>Payments are processed through Razorpay. Amaana&apos;s platform does not request or store full card details, UPI PINs, banking passwords or OTPs.</>],
["04","Documents and access",<>Applicant documents are stored privately and made available through short-lived links only to authorized staff. Public appeals contain only information approved for publication.</>],
["05","Analytics",<>The platform records aggregate daily counts for public page paths. It does not use analytics cookies, store IP addresses for analytics, or track assistance, donation, acknowledgement or admin pages.</>],
["06","Retention and disclosure",<>Records are retained only as long as reasonably necessary for case administration, accounting, security and applicable legal requirements. Information may be shared with service providers necessary to operate storage, hosting, communications and payments, or when required by law.</>],
["07","Your choices",<>You may request correction of inaccurate information or ask questions about the handling of your data by emailing <a href="mailto:amaanafoundation24@gmail.com">amaanafoundation24@gmail.com</a>. Some records may need to be retained for legitimate accounting, legal or fraud-prevention purposes.</>]
] as const;
export default function PrivacyPage(){return <div className="v2-policy-page"><section className="v2-policy-hero"><div className="v2-shell"><p className="v2-section-label">Last updated · 9 September 2026</p><h1>Privacy is part<br/>of <em>dignity.</em></h1><p>We collect only the information needed to review assistance requests, process donations, maintain records and operate the platform safely.</p></div></section><section className="v2-policy-principles"><div className="v2-shell"><div><span>Collect carefully</span><strong>Only what the work needs.</strong></div><div><span>Protect privately</span><strong>Sensitive evidence is not public content.</strong></div><div><span>Share deliberately</span><strong>Publication requires a separate decision.</strong></div></div></section><section className="v2-policy-body"><div className="v2-shell v2-policy-layout"><aside><p>Privacy policy</p><strong>Information entrusted to Amaana should be handled with the same care as the request itself.</strong><Link href="/request-assistance">Request assistance →</Link></aside><div className="v2-policy-sections">{sections.map(([n,title,body])=><article key={n}><span>{n}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></div></section></div>}
