import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { PolicyToc } from "@/components/policy-toc";
import styles from "./privacy-audit.module.css";
export const metadata: Metadata = {
  title: "Privacy Notice",
  description: "How Amaana Foundation currently collects, uses and protects personal information.",
  alternates: { canonical: "/privacy" },
  openGraph: { images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Amaana Foundation" }], type: "website", url: "/privacy", title: "Privacy Notice | Amaana Foundation", description: "How Amaana Foundation currently handles personal information." },
  twitter: { images: ["/twitter-image"], card: "summary", title: "Privacy Notice | Amaana Foundation", description: "How Amaana Foundation currently handles personal information." },
};
const sections=[
["01","Information we collect",<>Depending on the interaction, Amaana may collect names, contact details, location, enquiries, donation references and assistance-request information. Assistance records may include medical, financial, education or other supporting documents relevant to verification. Staff accounts also contain identity, role and audit information.</>],
["02","Why information is used",<>Information is used to respond to enquiries, review and verify assistance requests, determine support, administer appeals, process and reconcile donations, communicate relevant status changes, prevent misuse, secure the platform, maintain accountability records and meet applicable accounting or legal obligations.</>],
["03","Private assistance evidence",<>Documents submitted for assistance are for verification and administration, not automatic public display. Private proofs are stored separately from public campaign media and access is limited to authorised staff through short-lived links. Access to private documents is auditable.</>],
["04","Public stories require a separate decision",<>Submitting an assistance request or proof does not itself grant permission to publish a person&apos;s name, photograph, medical details, financial circumstances or institution information. If a public appeal is considered, disclosure permissions and privacy level are reviewed separately before public copy or media is approved.</>],
["05","Payments",<>Payments are processed through Razorpay. Amaana&apos;s platform does not request or store full card details, UPI PINs, banking passwords or OTPs. Amaana retains the transaction references and donor information needed for payment reconciliation, acknowledgement, security and applicable records.</>],
["06","Analytics and technical records",<>The platform records aggregate daily counts for public page paths. It does not use those analytics to track assistance, donation acknowledgement or admin pages. Separate hashed technical records may be used for security and abuse-rate limiting without retaining raw IP addresses in those counters.</>],
["07","Sharing",<>Information is shared only where reasonably necessary, such as with authorised Amaana staff, hosting/storage and communication providers, the payment processor, professional advisers, or hospitals/vendors/providers involved in verified assistance. Beneficiary or donor personal information is not sold.</>],
["08","Retention and access",<>Records are kept only as long as reasonably needed for assistance administration, accounting, security, audit, safeguarding, disputes and applicable requirements. Sensitive evidence receives restricted access; final statutory retention periods remain subject to professional confirmation.</>],
["09","Questions, correction and publication concerns",<>You may ask questions, report inaccurate information or raise a privacy/publication concern by emailing <a href="mailto:amaanafoundation24@gmail.com">amaanafoundation24@gmail.com</a>. Some records may need to be retained for legitimate accounting, legal, safeguarding or fraud-prevention purposes. Final statutory-rights wording will be aligned with the law applicable at launch.</>]
] as const;
export default function PrivacyPage(){return <div className="v2-policy-page"><PageHero variant="trust" eyebrow="Trust & Policies" title="Privacy is part of dignity." description={<p>Amaana collects information to verify need, deliver support, process legitimate organisational activity and maintain accountability — not to make private hardship public. Final legal wording remains subject to professional review.</p>} visualKicker="Privacy Notice" visualTitle="Private By Default" visualNote="Sensitive evidence is verification material, not public content. Publication requires a separate reviewed decision."/><section className="v2-policy-principles"><div className="v2-shell"><div><span>Collect carefully</span><strong>Only what the work reasonably needs.</strong></div><div><span>Protect privately</span><strong>Sensitive evidence is not public content.</strong></div><div><span>Share deliberately</span><strong>Publication requires a separate decision.</strong></div></div></section><section className={styles.matrix} aria-labelledby="privacy-data-classes"><div className="v2-shell"><h2 id="privacy-data-classes" className="sr-only">How information is treated</h2><div className={styles.matrixGrid}><article><span>Public-facing</span><h2>Published deliberately</h2><p>Stories, appeal context and media appear publicly only after the relevant publication and privacy review.</p></article><article><span>Private verification</span><h2>Restricted by default</h2><p>Assistance requests and supporting medical, financial or education evidence are used for verification and administration, not automatic public display.</p></article><article><span>Payment & accounting</span><h2>References, not banking secrets</h2><p>Amaana retains the donor and transaction information needed for reconciliation and records. Full card details, UPI PINs, banking passwords and OTPs are not requested or stored by the platform.</p></article></div></div></section><section className="v2-policy-body"><div className="v2-shell v2-policy-layout"><aside><p>Privacy notice</p><strong>Information entrusted to Amaana should be handled with the same care as the request itself.</strong><Link href="/request-assistance">Request assistance →</Link><Link href="/terms">Terms of use →</Link><PolicyToc items={sections.map(([n,title])=>({id:`policy-${n}`,label:title}))}/></aside><div className="v2-policy-sections">{sections.map(([n,title,body])=><article id={`policy-${n}`} key={n}><span>{n}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></div></section></div>}
