import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import styles from "./refund-audit.module.css";
export const metadata: Metadata = {
  title: "Refund Policy",
  description: "How to report an erroneous, duplicate or unauthorised donation to Amaana Foundation.",
  alternates: { canonical: "/refund-policy" },
  openGraph: { type: "website", url: "/refund-policy", title: "Refund Policy | Amaana Foundation", description: "How Amaana reviews donation payment and refund requests." },
  twitter: { card: "summary", title: "Refund Policy | Amaana Foundation", description: "How Amaana reviews donation payment and refund requests." },
};
const sections=[
["01","Requesting review",<>If you believe a donation was duplicated, entered incorrectly or processed without authorisation, contact <a href="mailto:amaanafoundation24@gmail.com">amaanafoundation24@gmail.com</a> promptly with the Amaana donation reference, payment reference if available, date, amount and a short description of the issue.</>],
["02","Assessment",<>Each request is reviewed against Amaana&apos;s platform, payment-provider and accounting records. Approval is not automatic and may depend on transaction status, applicable requirements, payment-provider rules and whether funds have already been irreversibly applied to the designated charitable purpose. <strong>Never send a card number, UPI PIN, banking password or OTP.</strong></>],
["03","Refund method and timing",<>Where a refund is approved, Amaana will use an appropriate traceable method, preferably the original payment source where supported. Approved refund requests will be processed as promptly as reasonably possible through the applicable payment channel; bank and payment-provider timelines may vary.</>],
["04","Debited but not confirmed",<>If your account appears debited but the website does not confirm success, please retain the payment-provider confirmation and contact Amaana rather than immediately making the same donation again. The transaction can then be reconciled against provider records.</>],
["05","Accounting and tax records",<>Processed refunds are recorded against the original donation and reflected in the appeal&apos;s confirmed collection records. Where an acknowledgement or tax-related record is affected, Amaana will make the appropriate accounting correction; a refund does not preserve or guarantee any tax treatment.</>],
["06","Designated and Zakat funds",<>Amaana does not silently redirect donor intent. Designated and Zakat-related refund or reallocation questions require additional review against the stated purpose and Amaana&apos;s applicable accounting and religious process.</>]
] as const;
export default function RefundPolicyPage(){return <div className="v2-policy-page v2-policy-refund"><PageHero variant="trust" eyebrow="Trust & Policies" title="Errors deserve a fair review." description={<p>Genuine payment problems are reviewed from the actual transaction record. This page describes Amaana&apos;s current operating approach; final legal/accounting wording remains subject to professional and payment-provider review.</p>} visualKicker="Refund Policy" visualTitle="Evidence Before Outcome" visualNote="Payment concerns are handled securely, calmly and through traceable records—not banking secrets."/><section className="v2-policy-principles"><div className="v2-shell"><div><span>Report</span><strong>Share the reference, amount and issue.</strong></div><div><span>Review</span><strong>The transaction is checked against records.</strong></div><div><span>Outcome</span><strong>Approved refunds use a traceable payment route.</strong></div></div></section><section className="v2-policy-body"><div className="v2-shell"><aside className={styles.securityCallout} aria-labelledby="refund-security-title"><span aria-hidden="true" className={styles.shield}>!</span><div><p className={styles.kicker}>Payment security</p><h2 id="refund-security-title">Amaana will never ask for your PIN, OTP, banking password or full card number.</h2><p>For refund review, share only the Amaana donation reference, payment reference if available, date, amount and a short description of the issue.</p></div></aside></div><div className="v2-shell v2-policy-layout"><aside><p>Refund policy</p><strong>A payment problem should be handled calmly, securely and from evidence — never by asking for banking secrets.</strong><a href="mailto:amaanafoundation24@gmail.com">Contact payment support →</a><Link href="/donation-policy">Donation policy →</Link></aside><div className="v2-policy-sections">{sections.map(([n,title,body])=><article key={n}><span>{n}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></div></section></div>}
